#!/usr/bin/env bash
# Turnkey installer for the Valenius Community edition (self-hosted, AGPLv3).
#
# Builds the backend image, generates strong random secrets, writes an .env +
# docker-compose.yml into ./valenius, starts the stack, and prints the login
# details on success. Mirrors documentation/docs/self-hosting/community.md —
# keep the two in sync if you change this script.
#
# Usage:
#   ./install.sh                # interactive
#   ADMIN_EMAIL=me@example.com BACKEND_PORT=9001 ./install.sh --yes   # non-interactive
#
# Re-running after a successful install refuses to touch existing secrets;
# pass --force to wipe ./valenius and start over.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

DEPLOY_DIR="valenius"
IMAGE_TAG="valenius-backend:latest"
FORCE=0
ASSUME_YES=0

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --yes|-y) ASSUME_YES=1 ;;
    --help|-h)
      sed -n '2,15p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

log()  { printf '\033[1;34m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$1" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$1" >&2; exit 1; }

# ── Preflight ─────────────────────────────────────────────────────────────

[ -f "Backend/Dockerfile" ] || die "Run this from the repo root (Backend/Dockerfile not found here)."

# chmod +x install.sh (needed to run it at all) makes git track an executable-bit
# change, which then collides with "git pull" on the next upgrade ("your local changes
# to install.sh would be overwritten"). Git only supports ignoring mode changes
# repo-wide (there's no per-file equivalent), which is fine for a deployment checkout.
# No-op if this isn't a git checkout (e.g. a downloaded tarball).
if git rev-parse --git-dir >/dev/null 2>&1; then
  git config core.fileMode false
fi

command -v docker >/dev/null 2>&1 || die "Docker is not installed or not on PATH. Install Docker Engine first."
docker compose version >/dev/null 2>&1 || die "The 'docker compose' plugin is not available. Install/update Docker."

if [ "$FORCE" = "1" ] && [ -d "$DEPLOY_DIR" ]; then
  warn "Removing existing $DEPLOY_DIR (--force)."
  rm -rf "$DEPLOY_DIR"
fi

if [ -f "$DEPLOY_DIR/.env" ]; then
  die "$DEPLOY_DIR/.env already exists — refusing to overwrite existing secrets. Re-run with --force to wipe and start over, or run 'docker compose -f $DEPLOY_DIR/docker-compose.yml up -d' to (re)start the existing install."
fi

# ── Gather settings ──────────────────────────────────────────────────────

ADMIN_EMAIL="${ADMIN_EMAIL:-}"
BACKEND_PORT="${BACKEND_PORT:-9001}"

if [ "$ASSUME_YES" != "1" ]; then
  read -r -p "Admin email for the bootstrap login [admin@example.com]: " input_email || true
  ADMIN_EMAIL="${input_email:-${ADMIN_EMAIL:-admin@example.com}}"

  read -r -p "Host port for the backend [9001]: " input_port || true
  BACKEND_PORT="${input_port:-$BACKEND_PORT}"
else
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"
fi

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

DB_PASSWORD="$(random_secret)"
ADMIN_PASSWORD="$(random_secret)"

# ── Build the image ──────────────────────────────────────────────────────

log "Building $IMAGE_TAG from Backend/Dockerfile (this can take a few minutes)..."
docker build -f Backend/Dockerfile -t "$IMAGE_TAG" .

# ── Write deploy files ───────────────────────────────────────────────────

log "Writing $DEPLOY_DIR/.env and $DEPLOY_DIR/docker-compose.yml..."
mkdir -p "$DEPLOY_DIR/data/downloads"

cat > "$DEPLOY_DIR/.env" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit this file.
DB_PASSWORD=${DB_PASSWORD}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
BACKEND_PORT=${BACKEND_PORT}
EOF

cat > "$DEPLOY_DIR/docker-compose.yml" <<'EOF'
name: valenius

services:
  db:
    container_name: valenius-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: valenius
      POSTGRES_USER: valenius
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - valenius-database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U valenius -d valenius"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: valenius-backend
    image: valenius-backend:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: ""
      ConnectionStrings__DefaultConnection: >-
        Host=db;Port=5432;Database=valenius;Username=valenius;Password=${DB_PASSWORD}
      DataProtection__KeysPath: /app/keys
      Valenius__ManifestPath: /app/data/versions.json
      Valenius__DownloadsPath: /app/data/downloads
      Valenius__AdminEmail: ${ADMIN_EMAIL}
      Valenius__AdminPassword: ${ADMIN_PASSWORD}
    volumes:
      - ./data:/app/data
      - valenius-keystore:/app/keys
    ports:
      - "${BACKEND_PORT}:8080"

volumes:
  valenius-database-data:
  valenius-keystore:
EOF

# ── Start it ──────────────────────────────────────────────────────────────

log "Starting the stack..."
( cd "$DEPLOY_DIR" && docker compose up -d )

log "Waiting for the backend to come up..."
READY=0
for _ in $(seq 1 30); do
  if ( cd "$DEPLOY_DIR" && docker compose logs backend 2>/dev/null ) | grep -q "Now listening on:"; then
    READY=1
    break
  fi
  sleep 2
done

if [ "$READY" != "1" ]; then
  warn "Backend didn't report ready within 60s. Check logs with:"
  warn "  docker compose -f $DEPLOY_DIR/docker-compose.yml logs -f backend"
  warn "Your generated credentials are saved in $DEPLOY_DIR/.env — nothing was lost."
  exit 1
fi

# ── Success ───────────────────────────────────────────────────────────────

cat <<EOF

✅ Valenius Community is up.

  URL:            http://localhost:${BACKEND_PORT}/
  Admin email:    ${ADMIN_EMAIL}
  Admin password: ${ADMIN_PASSWORD}

  These are also saved in $DEPLOY_DIR/.env (not committed to git — keep it safe).

Next steps:
  1. Log in and change the bootstrap password (Admin -> Users), or set up OIDC/SSO
     under Admin -> Settings.
  2. Put a TLS-terminating reverse proxy in front before exposing this beyond
     localhost — OIDC login and secure cookies require real HTTPS.
     See: documentation.valenius.com/self-hosting/community (step 6)
  3. Admin -> Customers to create your first customer, then upload a WireGuard
     client .conf under Admin -> [client] -> Details.

To stop:    (cd $DEPLOY_DIR && docker compose down)
To restart: (cd $DEPLOY_DIR && docker compose up -d)
EOF
